config/urls.py
# config/urls.py

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/urls.py
#  hello/urls.py

from django.shortcuts import render
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "portfolio"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('home', views.home_page_view, name='home'),
    path('apresentacao', views.apresentacao_view, name='apresentacao'),
    path('cadeiras/<int:id>', views.cadeira_view, name='cadeira'), 
    path('edita-cadeira/<int:cadeira_id>', views.edita_cadeira_view, name='editar_cadeira'),
    path('apaga-cadeira/<int:cadeira_id>', views.apaga_cadeira_view, name='apagar_cadeira'),
    path('nova-cadeira/', views.nova_cadeira_view, name='novo_cadeira'),

    path('projetos', views.projetos_view, name='projetos'),
    path('edita-projeto/<int:projeto_id>', views.edita_projeto_view, name='editar_projeto'),
    path('apaga-projeto/<int:projeto_id>', views.apaga_projeto_view, name='apagar_projeto'),
    path('novo-projeto/', views.novo_projeto_view, name='novo_projeto'),

    path('edita-tfc/<int:tfc_id>', views.edita_tfc_view, name='editar_tfc'),
    path('apaga-tfc/<int:tfc_id>', views.apaga_tfc_view, name='apagar_tfc'),
    path('novo-tfc/', views.novo_tfc_view, name='novo_tfc'),

    path('web', views.web_view, name='web'),
    path('descricaoWeb/<int:id>', views.descricaoWeb_view, name='descricaoWeb'),
    path('quizz', views.quizz_view, name='quizz'),
    path('blog', views.blog_view, name='blog'), 
    path('contactos', views.contactos_view, name='contactos'),
    path('login/', views.view_login, name='login'),
    path('logout/', views.view_logout, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
from statistics import mode
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class Pessoa(models.Model):
    nome = models.CharField(max_length =64)
    linkPaginaLusofona = models.URLField(default = "",blank = True)
    linkPaginaLinkedin = models.URLField(default = "", blank = True)

    def __str__(self):
        return self.nome


class Cadeira(models.Model):
    nome = models.CharField(max_length = 64)
    ano = models.IntegerField(default = 1)
    semestre = models.IntegerField(default = 1, choices = [(1, "semestre 1"), (2, "semestre 2"),(3, "anual")])
    ects = models.IntegerField(default = 6, validators = [MinValueValidator(limit_value = 1), MaxValueValidator(limit_value = 20)])
    anoLetivoFrequentado = models.IntegerField(default = 2020)
    topicosAbordados = models.CharField(default = "", blank = True, max_length = 1024)
    ranking = models.IntegerField(default = 3, choices = [(1, "1 estrela"), (2, "2 estrelas"),(3, "3 estrelas"), (4, "4 estrelas"), (5, "5 estrelas")])
    linkCadeira = models.URLField(default = "", blank = True)
    professores = models.ManyToManyField(Pessoa, blank = True)
    
    def __str__(self):
        return self.nome


class Projeto(models.Model):
    titulo = models.CharField(max_length = 64)
    descricao = models.CharField(default = "", blank = True, max_length = 500)
    imagem = models.ImageField(default = "", blank = True)
    anoRealizacao = models.IntegerField(default = 2020)
    cadeira = models.ForeignKey(Cadeira, null = True, blank = True, on_delete = models.SET_NULL)
    participantes = models.ManyToManyField(Pessoa, blank = True)

    def __str__(self):
        return self.titulo
    

class Formacao(models.Model):
    curso = models.CharField(max_length = 64)
    local = models.CharField(default = "", blank = True, max_length = 64)
    periodo = models.DateField(blank = True)
    logotipo = models.ImageField(blank = True)

    def __str__(self):
        return self.curso


class Competencia(models.Model):
    titulo = models.CharField(max_length = 64)
    descricao = models.CharField(default = "", blank = True, max_length = 512)
    projetos = models.ManyToManyField(Projeto, blank = True)
    disciplinaAplicada = models.ManyToManyField(Cadeira, blank = True)
    tecnologies = models.CharField(default = "", blank = True, max_length = 512)
    linguas = models.CharField(default = "", blank = True, max_length = 512)

    def __str__(self):
        return self.titulo


class Interesse(models.Model):
    titulo = models.CharField(max_length = 64)
    descricao = models.CharField(default = "", blank = True, max_length = 512)
    fotografia = models.ImageField(blank = True)
    link = models.URLField(blank = True)

    def __str__(self):
        return self.titulo


class Tecnologia(models.Model):
    nome = models.CharField(max_length = 64)
    acronimo = models.CharField(max_length = 64)
    anoDeCriacao = models.IntegerField(default = 1950, validators = [MinValueValidator(limit_value = 1900), MaxValueValidator(limit_value = 2022)])
    criador = models.CharField(max_length = 64)
    descricao = models.CharField(max_length = 512)
    siteOficial = models.URLField(default = "", blank = True)
    logotipo = models.ImageField(default = "", blank = True)

    def __str__(self):
        return self.nome

class Tfc(models.Model):
    titulo = models.CharField(max_length = 64)
    autor = models.ManyToManyField(Pessoa, blank = True, related_name='tfc_autor')
    orientador = models.ManyToManyField(Pessoa, blank = True, related_name='tfc_orientador')
    anoRealizacao = models.IntegerField(default = 2020)
    sumario = models.CharField(max_length = 64, blank = True)
    resumo = models.CharField(max_length = 500, blank = True)
    linkRelatorio = models.URLField(default = "", blank = True)
    linkGitHub = models.URLField(default = "", blank = True)
    videoYouTube = models.URLField(default = "", blank = True) 

    def __str__(self):
        return self.titulo
        

class Noticia(models.Model):
    titulo = models.CharField(max_length = 64)
    texto = models.CharField(max_length = 256)
    foto = models.ImageField(default = "", blank = True)
    link = models.URLField(default = "", blank = True)
    
    def __str__(self):
        return self.titulo


class Post(models.Model):
    autor = models.CharField(max_length = 64)
    titulo = models.CharField(max_length = 64)
    descricao = models.CharField(max_length = 256)
    link = models.URLField(default = "", blank = True)
    foto = models.ImageField(default = "", blank = True)

    def __str__(self):
        return self.titulo


class PontuacaoQuizz(models.Model):
    nome = models.CharField(max_length = 64)
    pontuacao = models.IntegerField(default = 0)

    def __str__(self):
        return self.nome

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

        labels = {
            'titulo': 'Título',
            'autor': 'Autor',
            'description': 'Post'
        }

        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'titulo do post'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'descrição do conteúdo'}),
            'autor': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'nome'}),
        }


class CadeiraForm(ModelForm):
    class Meta:
        model = Cadeira
        fields = '__all__'

        labels = {
            'titulo': 'Título',
            'autor': 'Autor',
            'description': 'Descrição'
        }

    nome = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'titulo do post'})
    ano = forms.NumberInput(attrs={'class': 'form-control', 'max': 3, 'min': 1})
    descricao = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'nome'})
    projetos = forms.ModelChoiceField(queryset=Projeto.objects.all())
    classificacao = forms.NumberInput(attrs={'class': 'form-control', 'max': 5, 'min': 1})


class ProjetoForm(ModelForm):
    class Meta:
        model = Projeto
        fields = '__all__'

        labels = {
            'titulo': 'Título',
            'autor': 'Autor',
            'description': 'Descrição'
        }

    nome = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'nome'})
    ano = forms.NumberInput(attrs={'class': 'form-control', 'max': 3, 'min': 1})
    descricao = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'descrição'})
    image = forms.ImageField


class AutorForm(ModelForm):
    class Meta:
        model = Pessoa
        fields = '__all__'

        labels = {
            'titulo': 'Título',
            'autor': 'Autor',
            'description': 'Descrição'
        }

    nome = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'nome'})


class TfcForm(ModelForm):
    class Meta:
        model = Tfc
        fields = '__all__'

        labels = {
            'titulo': 'Título',
            'autor': 'Autor',
            'description': 'Descrição'
        }

    nome = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'nome'})
    autores = forms.ModelMultipleChoiceField(queryset = Pessoa.objects.all())
    orientadores = forms.ModelMultipleChoiceField(queryset = Pessoa.objects.all())
    ano = forms.ImageField()
    titutlo = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'titulo'})
    description = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'description'})
    link = forms.URLField()
    linkgithub= forms.URLField()

portfolio/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


from .models import Cadeira, Pessoa, Projeto, Formacao, Competencia, Tecnologia, Post, Interesse, Noticia, PontuacaoQuizz, Tfc
from .forms import CadeiraForm, ProjetoForm

# Create your views here.
def view_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(
            request,
            username = username,
            password = password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('portfolio:home'))
        else:
            return render(request, 'portfolio/login.html', {'message': 'Credenciais invalidas.'})

    return render(request, 'portfolio/login.html')


def view_logout(request):
    logout(request)

    return render(request, 'portfolio/login.html', {'message': 'Foi desconetado.'})


def home_page_view(request):
	return render(request, 'portfolio/home.html')


def apresentacao_view(request):
	cadeiras = Cadeira.objects.all()

	map = {
		'ano1': {
			'semestre1': [],
			'semestre2': []
		},
		'ano2': {
			'semestre1': [],
			'semestre2': []
		},
		'ano3': {
			'semestre1': [],
			'semestre2': [],
			'semestre3': []
		}
	}

	for cadeira in cadeiras:
		map["ano" + str(cadeira.ano)]['semestre' + str(cadeira.semestre)].append(cadeira)
	
	competencias = Competencia.objects.all()
	interesses = Interesse.objects.all()
	formacoes = Formacao.objects.all()

	context = {'mapa': map, 'competencias': competencias,'interesses': interesses,'formacoes': formacoes}
		
	return render(request, 'portfolio/apresentacao.html', context)


def cadeira_view(request, id):
	cadeira = Cadeira.objects.get(pk = id)
	projetos = list(Projeto.objects.filter(cadeira = id))
	context = {'cadeira': cadeira, 'projetos': projetos, 'professores' : cadeira.professores.all() }

	return render(request, 'portfolio/cadeira.html', context)


@login_required
def edita_cadeira_view(request, cadeira_id):
    cadeira = Cadeira.objects.get(id = cadeira_id)
    form = CadeiraForm(request.POST or None, instance = cadeira)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:cadeira'))

    context = {'form': form, 'cadeira_id': cadeira_id}

    return render(request, 'portfolio/editar_cadeira.html', context)


@login_required
def apaga_cadeira_view(request, cadeira_id):
    Cadeira.objects.get(id = cadeira_id).delete()

    return HttpResponseRedirect(reverse('portfolio:cadeira'))


def nova_cadeira_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))

    form = CadeiraForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:cadeira'))

    context = {'form': form}

    return render(request, 'portfolio/nova_cadeira.html', context)


def projetos_view(request):
	projetos = Projeto.objects.all()
	tfcs = Tfc.objects.all()

	context = {'projetos': projetos, 'tfcs' : tfcs}

	return render(request, 'portfolio/projetos.html', context)


@login_required
def edita_projeto_view(request, projeto_id):
    projeto = Projeto.objects.get(id = projeto_id)
    form = ProjetoForm(request.POST or None, instance = projeto)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:projetos'))

    context = {'form': form, 'projeto_id': projeto_id}

    return render(request, 'portfolio/editar_projeto.html', context)


@login_required
def apaga_projeto_view(request, projeto_id):
    Projeto.objects.get(id = projeto_id).delete()

    return HttpResponseRedirect(reverse('portfolio:projetos'))


def novo_projeto_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))
    form = ProjetoForm(request.POST or None)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:projetos'))

    context = {'form': form}

    return render(request, 'portfolio/novo_projeto.html', context)


@login_required
def edita_tfc_view(request, tfc_id):
    tfc = Tfc.objects.get(id = tfc_id)
    form = ProjetoForm(request.POST or None, instance = tfc)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:projetos'))

    context = {'form': form, 'tfc_id': tfc_id}

    return render(request, 'portfolio/editar_tfc.html', context)


@login_required
def apaga_tfc_view(request, tfc_id):
    Tfc.objects.get(id = tfc_id).delete()

    return HttpResponseRedirect(reverse('portfolio:projetos'))


def novo_tfc_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))
    form = ProjetoForm(request.POST or None)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:projetos'))

    context = {'form': form}

    return render(request, 'portfolio/novo_projeto.html', context)


def web_view(request):
	tecnologias = Tecnologia.objects.all()
	noticias = Noticia.objects.order_by('?')[:10]
	context = {'tecnologias': tecnologias, 'noticias' : noticias}

	return render(request, 'portfolio/web.html', context)


def descricaoWeb_view(request, id):
	tecnologia = Tecnologia.objects.get(pk = id)
	context = {'tecnologia': tecnologia}
	
	return render(request, 'portfolio/descricaoWeb.html', context)


def quizz_view(request):
    p = 0

    if request.method == 'POST':
        n = request.POST['nome']
        p = pontuacao_quizz(request)
        r = PontuacaoQuizz(nome = n, pontos = p)
        r.save()
        desenha_grafico_resultados(r)

    context = {'pontos': p}

    return render(request, 'portfolio/quizz.html', context)


def pontuacao_quizz(request):
    pontos = 0
    form = request.POST

    if form['p1'] == 'Python':
        pontos += 1

    if form['p2'] == 'Web2py':
        pontos += 1

    if form['p3'] == '1995':
        pontos += 1

    if form['p4'] == 'Boa navegação':        
	     pontos += 1

    ##if form['p5'] == 'marcação':
        ##pontos += 1

    ##if form['p6'] == '53':
        ##pontos += 1	

	##if form['p7'] == '<iframe>':
        ##pontos += 1
	
    ##return pontos


def desenha_grafico_resultados():
    pontuacoes = sorted(PontuacaoQuizz.objects.all(), key=lambda x: x.pontos, reverse=True)

    pessoas_x = []
    pontos_y = []

    for resposta in pontuacoes:
        pessoas_x.append(resposta.nome)
        pontos_y.append(resposta.pontos)

    pessoas_x.reverse()
    pontos_y.reverse()


def blog_view(request):
	posts = Post.objects.order_by('?')[:6]
	context = {'posts': posts}	

	return render(request, 'portfolio/blog.html', context)


def contactos_view(request):
	return render(request, 'portfolio/contactos.html')

portfolio/templates/portfolio/blog.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <h2>Blog📝</h2>
    <div class="espacamento2"></div>
    <p>Nesta página, <i>Blog</i> irei mostrar 6 posts de comentários que colegas meus fizeram quando realizaram trabalhos/projetos comigo assim como uma pessoa determinada e com predisposição para ajudar o próximo.</p>
    <div class="espacamento"></div>

    <h3>Comentário de colegas com quem trabalhei:</h3>
    <div class="comentarios">       
        {% for post in posts %}
            <div>
                <h3>{{ post.titulo }}</h3>
                <br>
                <p>{{ post.descricao }}</p> 
                <br>
                <p>{{ post.autor }}</p>   
            </div>
        {% endfor %}
    </div>
{% endblock %}

portfolio/templates/portfolio/cadeira.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <h1>{{ cadeira.nome }}</h1>
    <div class="espacamento2"></div>
    <p>Informações relativamente à disciplina de {{ cadeira.nome }}:</p>
    <ul>
        <div class="espacamento">
            <li>Ano: {{ cadeira.ano }}</li>
            <li>Semestre: {{ cadeira.semestre }}</li>
            <li>ECTS: {{ cadeira.ects }}</li>
            <li>Ano Letivo frequentado: {{ cadeira.anoLetivoFrequentado }}</li>
            <li>Tópicos abordados: {{ cadeira.topicosAbordados }}</li>
            <li>Ranking: {{ cadeira.ranking }} estrelas</li>
            <div class="espacamento2"></div>
            <li>Professores:</li>
            <ul>
                {% for professor in professores %}
                    <div class="espacamento">
                        <li>Nome: {{ professor.nome }}</li>  
                        <li><a href="{{ professor.linkPaginaLusofona }}">Página da Lusófona</a></li>
                        {% if professor.linkPaginaLinkedin != "" %}
                            <li><a href="{{ professor.linkPaginaLinkedin }}">Página do LinkedIn</a></li>
                        {% endif %}
                    </div>   
                {% endfor %}
            </ul>

            <li>Projetos:</li>
            {% if not projetos %}
                <ul>
                    <div class="espacamento">
                        <li>Sem projetos.</li>
                    </div>
                </ul>             
            {% else %}
                <ul>
                    <div class="espacamento">
                        {% for projeto in projetos %}
                            <li>{{ projeto.titulo }}</li>
                        {% endfor %}
                    </div>
                </ul>
            {% endif %}
        </div>
    </ul>
    {% if request.user.is_authenticated %}
        <a href="{% url 'portfolio:editar_cadeira' cadeira.id %}">Editar</a>
    {% endif %}

    <div class="espacamento"></div>
    <a href="{% url 'portfolio:apresentacao' %}" class="espacamento">Voltar</a>
    
{% endblock %}

portfolio/templates/portfolio/contactos.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <h2>Contactos📞</h2>
    <div class="espacamento2"></div>
    <p>Nesta página disponibilizo diversas informações como links associados ao percurso académico bem como redes sociais, contacto, ano, universidade e logotipo.</p>
    <div class="espacamento2"></div>
    <div class="espacamento2"></div>
    <div class="espacamento2"></div>

    <p>Redes sociais e links para LinkedIn e GitHub:</p>
    <div class="espacamento">
        <a href= "https://www.linkedin.com/in/pedro-rocha-9a30aa209/">LinkedIn</a>
        <div class="espacamento2"></div>
        <a href="https://github.com/PedroRocha-a22003766">GitHub</a>
        <div class="espacamento2"></div>
        <a href="https://www.facebook.com/pedro.rocha.9876543210">Facebook</a>
        <div class="espacamento2"></div>
        <a href="">Instagram</a>
        <div class="espacamento2"></div>
    </div>
    <div class="espacamento"></div>

    <h2>Rodapé💼</h2>
    <div class="espacamento2"></div>
    <div class="espacamento2"></div>
    <div class="espacamento2"></div>
    <p>Contactos e informações académicas:</p>
    <div class="espacamento">
        <a href="">🗺️ Mapa do Site</a>
        <div class="espacamento2"></div>
        <p>📞 Contacto : +351 969 253 565</p>
        <div class="espacamento2"></div>
        <p>🧑 Autor : Pedro Miguel Martins Rocha</p>
        <div class="espacamento2"></div>
        <p>🥈 Ano : 2º ano</p>
        <div class="espacamento2"></div>
        <p>⛪ Universidade : Universidade Lusófona de Humanidades e Tecnologias</p>
        <div class="espacamento2"></div>
        <p>📜 Logotipo : </p>
        <div class="espacamento2"></div>
        {% load static %}
        <img src="{% static 'portfolio/images/logo_ulht.jpg' %}" alt="LogotipoFaculdade">
    </div>
    
{% endblock %}

portfolio/templates/portfolio/descricaoWeb.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <h1>{{ tecnologia.nome }} ({{ tecnologia.acronimo }})</h1>
    <div class="espacamento2"></div>
    <div class="espacamento2"></div>
    <p>Nesta página serão abordados conteúdos específicos em relação ao {{ tecnologia.acronimo }} como nome, acrónimo, ano de criação, criador, descrição, logotipo e o link para site oficial.</p> 

    <ul>
        <div class="espacamento">
            <li>Nome : {{ tecnologia.nome }};</li>
            <div class="espacamento2"></div>
            <li>Acrónimo : {{ tecnologia.acronimo }};</li>
            <div class="espacamento2"></div>
            <li>Ano de criação : {{ tecnologia.anoDeCriacao }};</li>
            <div class="espacamento2"></div>
            <li>Criador : {{ tecnologia.criador }};</li>
            <div class="espacamento2"></div>
            <li>Descrição : {{ tecnologia.descricao }}</li>
            <div class="espacamento2"></div>
            <li>Site Oficial : <a href="{{ tecnologia.siteOficial }}">Clique Aqui para aceder ao site oficial!</a></li>
            <div class="espacamento2"></div>
            <li>Logotipo :</li>
            <div class="espacamento2"></div>
            <img src="/portfolio/static/portfolio/images/{{ tecnologia.logotipo }}" alt="Logotipo">
        </div>
    </ul>
    
    <a href="{% url 'portfolio:web' %}" class="espacamento">Voltar</a>
{% endblock %}

portfolio/templates/portfolio/editar_cadeira.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <h2>Editar Cadeira</h2>
    <form action="{% url 'portfolio:editar_cadeira' cadeira_id %}" method="POST">

        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>

        <input type="submit" value="Salvar">
        <div class="espacamento"></div>
        <a href="{% url 'portfolio:apresentacao' %}">Cancelar</a>
        <a href="{% url 'portfolio:apagar_cadeira' cadeira_id %}">Apagar</a>
    </form>
{% endblock %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Pedro Rocha">
        <meta name="keywords" content="Front-end, Back-end">
        <meta name="description" content="Portfolio">
        {% load static %}
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'portfolio/images/papel.ico' %}">
        {% load static %}
        <link rel="stylesheet" href="{% static 'portfolio/css/layout.css' %}">
        <script>
            function showTime() {
                var time =  new Date();
                var hora = time.getHours();
                var minuto = time.getMinutes();
                var segundo = time.getSeconds();
            
                if(hora < 10) hora = "0" + hora;
                if(minuto < 10) minuto = "0" + minuto;
                if(segundo < 10) segundo = "0" + segundo;
            
                var tempo = hora + ":" + minuto + ":" + segundo;
            
                document.getElementById("timer").innerHTML = tempo;
            }
        
            function initTime() {
                setInterval(showTime, 1000);
            }
        </script>

        <title>Portfólio Digital</title>
    </head> 
    <body onload="initTime();">
        <header>
            <div>Pedro Rocha 🎓</div>
            <nav>
              <a href="{% url 'portfolio:home' %}">Home🏡</a>       
              <a href="{% url 'portfolio:apresentacao' %}">Apresentação📋</a>      
              <a href="{% url 'portfolio:projetos' %}">Projetos📑</a>      
              <a href="{% url 'portfolio:web' %}">Web🌐</a>      
              <a href="{% url 'portfolio:blog' %}">Blog📝</a>
              <a href="{% url 'portfolio:contactos' %}">Contactos📞</a>
            </nav>
        </header>
          
        <main>
            {% block main %}
            {% endblock main %}
        </main>
        <center><p id="timer" class="timer"></p></center>

        <footer>ULHT, 2022</footer>
            
    </body>
</html>

portfolio/templates/portfolio/nova_cadeira.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <h2>Nova Cadeira</h2>
    
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        
        <div class="espacamento"></div>
        <a href="{% url 'portfolio:apresentacao' %}">Cancelar</a>
        <input type="submit" value="Gravar">
    </form>
{% endblock %}

portfolio/templates/portfolio/projetos.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <div class="ancoras">
        <a href="#Projetos">Projetos</a> | <a href="#ProjetosPorMim">Projetos realizados por mim</a> | <a href="#ProjetosFinalCurso">Projetos de fim de curso interessantes</a>
    </div>
    <div class="espacamento"></div>

    <h2 id="Projetos">Projetos...📑</h2>
    <div class="espacamento2"></div>
    <p>Nesta página irei apresentar todos os projetos que foram realizados por mim, seja pela faculdade, seja por livre vontade.</p>
    <div class="espacamento2"></div>
    <p>Irei apresentar, também, trabalhos/projetos de fim de curso bastante interessantes e cativadores.</p>
    <div class="espacamento"></div>

    <ol>
        <li><h3 id="ProjetosPorMim">...realizados por mim</h3></li>
        <div class="espacamento">
            {% for projeto in projetos %}
                <ul style="list-style-type:square">
                    <li>{{ projeto.titulo }};</li>
                </ul> 
            {% endfor %}
        </div>

        {% if request.user.is_authenticated %}
            <a href="{% url 'portfolio:novo_projeto' %}" class="button">Novo Projeto</a>
        {% endif %}
        <div class="espacamento"></div>

        <li><h3 id="ProjetosFinalCurso">...de fim de curso interessantes</h3></li>
        <div class="espacamento">
            <div class="tfc">       
                {% for tfc in tfcs %}
                    <div>
                        <h3>{{ tfc.titulo }}</h3>
                        <br>
                        <p>{{ tfc.resumo }}</p> 
                        <br>
                        {% for autor in tfc.autores.all %}
                            {{ autor }}
                        {% endfor %}
    
                        {% for orientador in tfc.orientadores.all %}
                            {{ orientador }}
                        {% endfor %}
                        <a href="{{ tfc.linkRelatorio }}  ">Relatorio</a>
                        <a href="{{ tfc.linkgithub }} ">Github</a>
                    </div>
                {% endfor %}
            </div>
        </div>
        
        <div class="espacamento"></div>
        {% if request.user.is_authenticated %}
            <a href="{% url 'portfolio:novo_tfc' %}" class="button">Novo Tfc</a>
        {% endif %}
    </ol>
{% endblock %}